name: Build & Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup
        run: |
          git clone --depth=1 https://github.com/keiyoushi/extensions-source.git build-env

          echo "=== ARCHIVOS GRADLE ==="
          find build-env -name "*.gradle*" | sort

          echo "=== COMMON ==="
          find build-env -name "common.gradle" | sort

          echo "=== SETTINGS ==="
          find build-env -name "settings.gradle*" | sort

      - name: Stop after debug
        run: exit 1
