name: Build & Publish

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone extensions-source
        run: |
          git clone --depth=1 https://github.com/keiyoushi/extensions-source.git build-env

      - name: Show sample build.gradle
        run: |
          echo "=== TOPTOON BUILD.GRADLE ==="
          cat build-env/src/zh/toptoon/build.gradle

          echo ""
          echo "=== SETTINGS ==="
          cat build-env/settings.gradle.kts

          exit 1
